import test from 'node:test';
import assert from 'node:assert/strict';
import {observerApi,decodeObserverPage,decodeObserverTicket,observerStreamUrl} from '../dist/api/observer-v2.js';
import {runObserverScreen} from '../dist/runtime/observer-screen.js';
import {encodeTerminalFrame} from '../dist/terminal/codec.js';
const id=n=>`ba600000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const project='20178adc-8ae4-515a-bb38-bd25042707db',principal=id(1);
const grant={version:'2',kind:'session_observe_grant',grant_id:id(3),revision:1,owner_principal_id:id(4),subject_principal_id:principal,agent_session_id:id(5),session_incarnation:id(6),project_id:project,authority_epoch:1,membership_revision:1,state:'active',expires_at:Date.now()+60000,revocation_state:null};
const ticket={version:'2',attachment_id:id(7),expires_at:Date.now()+10000,secret:'x'.repeat(43),stream_path:`/v1/collaboration/2/observer-attachments/${id(7)}/stream`};
const page={version:'2',kind:'observer_sessions',project_id:project,items:[grant],next_after_grant_id:null};
const tick=()=>new Promise(resolve=>setTimeout(resolve,25));
test('canonical v5 Project discovery binds recipient and ticket strictly',async()=>{let calls=0;const api=observerApi({request:async()=>{calls++;return page;}},principal,project);assert.equal((await api.list(null,new AbortController().signal)).items.length,1);assert.equal(calls,1);for(const bad of [{...page,project_id:id(9)},{...page,items:[{...grant,subject_principal_id:id(9)}]},{...page,items:[grant,grant]}])assert.throws(()=>decodeObserverPage(bad,principal,project,null));assert.equal(observerStreamUrl(ticket,'https://api.getcuna.com'),'wss://api.getcuna.com'+ticket.stream_path);for(const origin of ['https://api.getcuna.com.evil','http://api.getcuna.com','https://user@api.getcuna.com'])assert.throws(()=>observerStreamUrl(ticket,origin));assert.throws(()=>decodeObserverTicket({...ticket,stream_path:ticket.stream_path+'?secret=x'},grant));});
test('identity change while ticket is pending refuses the result',async()=>{let owner=principal;const api=observerApi({request:async()=>{owner=id(9);return ticket;}},principal,project,async()=>owner);await assert.rejects(api.issue(grant,id(8),'client-B',new AbortController().signal));});
function harness(issue=async()=>ticket){let input,restored=0,closed=0;const frames=[],sockets=[],requests=[];const host={dimensions:()=>({columns:80,rows:24}),acquire:async()=>({restore:async()=>{restored++;}}),write:async bytes=>{frames.push(new TextDecoder().decode(bytes));},onInput(fn){input=fn;return()=>{input=undefined;};},onResize(){throw Error('resize listener forbidden');}};const api={list:async()=>page,issue:async(...args)=>{requests.push(args);return issue(...args);}};const done=runObserverScreen(api,'https://api.getcuna.com',host,undefined,(url,protocols)=>{const socket={url,protocols,close(){closed++;}};sockets.push(socket);return socket;});return{done,frames,sockets,requests,key(value){input?.(new TextEncoder().encode(value));},get restored(){return restored;},get closed(){return closed;}};}
function output(sequence,text){return encodeTerminalFrame({type:'output',sequence,critical:true,payload:new TextEncoder().encode(text)}).buffer;}
test('interactive observer renders verified output; typing has no send path and close restores terminal',async()=>{const h=harness();await tick();h.key('\r');await tick();assert.equal(h.sockets.length,1);const socket=h.sockets[0];assert.deepEqual(socket.protocols,['runa.terminal.v1','runa.auth.'+ticket.secret]);assert.ok(!socket.url.includes(ticket.secret));socket.onmessage({data:output(2n,'nonce-visible')});await tick();assert.ok(h.frames.some(f=>f.includes('nonce-visible')));h.key('typed-secret');assert.equal(h.requests.length,1);h.key('\x03');await h.done;assert.equal(h.restored,1);assert.equal(h.closed,1);assert.ok(!h.frames.join('').includes(ticket.secret));});
test('close during admission fences late result and restores once without opening a socket',async()=>{let resolve;const pending=new Promise(r=>{resolve=r;});const h=harness(()=>pending);await tick();h.key('\r');await tick();h.key('\x1b');await h.done;resolve(ticket);await tick();assert.equal(h.sockets.length,0);assert.equal(h.restored,1);});
test('non-output or regressing frames end observation; explicit reconnect uses fresh identities',async()=>{const h=harness();await tick();h.key('\r');await tick();const first=h.sockets[0];first.onmessage({data:output(2n,'A')});await tick();first.onmessage({data:output(2n,'B')});await tick();assert.ok(h.frames.some(f=>f.includes('could not be verified')));h.key('r');await tick();assert.equal(h.sockets.length,2);assert.notEqual(h.requests[0][1],h.requests[1][1]);first.onerror();h.sockets[1].onmessage({data:output(1n,'new-stream')});await tick();assert.ok(h.frames.some(f=>f.includes('new-stream')));h.key('\x03');await h.done;});
test('verified first frame outlives ticket acquisition expiry without forced disconnect',async()=>{const short={...ticket,expires_at:Date.now()+500};const h=harness(async()=>short);await tick();h.key('\r');await tick();h.sockets[0].onmessage({data:output(1n,'established')});await new Promise(resolve=>setTimeout(resolve,550));assert.equal(h.closed,0);h.key('\x03');await h.done;});
import {memoryStreams,runCli} from '../dist/index.js';
test('observe preflight rejects non-TTY, JSON and invalid Project before credentials; help is available',async()=>{
 let reads=0;const platform={kind:'linux',paths:{configDirectory:'/cfg',stateDirectory:'/state',runtimeDirectory:'/run'},async readSafeConfig(){reads++;throw Error('must not read configuration');}};
 for(const argv of [['observe','--project',project],['observe','--project',project,'--json'],['observe','--project','invalid']]){const s=memoryStreams();assert.notEqual(await runCli(argv,{streams:s.streams,platform}),0);}
 assert.equal(reads,0);const s=memoryStreams();assert.equal(await runCli(['observe','--help'],{streams:s.streams,platform}),0);assert.match(s.stdout(),/observe --project/);assert.match(s.stdout(),/read-only/i);
});
test('blocked host paint and close discard queued remote output before terminal restoration',async()=>{
 let input,release,restored=0,socket;const frames=[];const blocked=new Promise(r=>{release=r;});
 const host={dimensions:()=>({columns:80,rows:24}),acquire:async()=>({restore:async()=>{restored++;}}),write:async bytes=>{const text=new TextDecoder().decode(bytes);frames.push(text);if(text.includes('first-visible'))await blocked;},onInput(fn){input=fn;return()=>{};},onResize(){throw Error('forbidden');}};
 const done=runObserverScreen({list:async()=>page,issue:async()=>ticket},'https://api.getcuna.com',host,undefined,()=>socket={close(){}});
 await tick();input(new TextEncoder().encode('\r'));await tick();socket.onmessage({data:output(1n,'first-visible')});await tick();socket.onmessage({data:output(2n,'must-not-paint')});socket.onclose();release();await tick();assert.ok(!frames.join('').includes('must-not-paint'));input(new Uint8Array([3]));await done;assert.equal(restored,1);
});
