import assert from 'node:assert/strict';
import test from 'node:test';
import {runProviderScreen} from '../dist/machines/provider-screen.js';
import {decodeProviderObservation,decodeProviderPresets} from '../dist/api/provider-v2.js';
class Host{screen='';restored=0;dimensions(){return {columns:120,rows:20};}async acquire(){return {restore:async()=>{this.restored++;}};}async write(b){this.screen=new TextDecoder().decode(b);}onInput(f){this.input=f;return()=>{this.input=undefined;};}onResize(){return()=>{};}key(s){this.input?.(new TextEncoder().encode(s));}}
async function see(h,s){for(let i=0;i<200;i++){if(h.screen.includes(s))return;await new Promise(r=>setTimeout(r,5));}assert.fail(h.screen);}
const id='10000000-0000-4000-8000-000000000001';const preset={kind:'provider_preset',agent:'opencode',label:'OpenCode Zen / Big Pickle',profile_id:id,profile_revision:1};
test('actual preset screen requires explicit selection and ignores pasted Enter',async()=>{const host=new Host();const run=runProviderScreen({getProviderPresetsV2:async()=>[preset]},{kind:'preset',agent:'opencode'},host);await see(host,preset.label);host.key('\x1b[200~\r\x1b[201~');await new Promise(r=>setTimeout(r,20));assert.equal(host.restored,0);host.key('\r');assert.deepEqual(await run,preset);assert.equal(host.restored,1);});
test('check screen clears identity after expiry and failed explicit refresh; no polling',async()=>{const host=new Host();let pulls=0;const client={getAgentSession:async()=>({id,processEpoch:id,desiredState:'running',processState:'running'}),checkProviderV2:async()=>{pulls++;if(pulls>1)throw Error('unavailable');return {state:'observed',observed_at_ms:Date.now()-1,valid_until_ms:Date.now()+70,provider:{upstream_provider:'opencode',model:'big-pickle',agent_version:'1.2.3'}};}};const run=runProviderScreen(client,{kind:'check',sessionId:id},host);await see(host,'big-pickle');await see(host,'expired');assert.doesNotMatch(host.screen,/big-pickle/);assert.equal(pulls,1);host.key('r');await see(host,'unavailable');assert.equal(pulls,2);host.key('q');await run;});
test('strict V2 decoder refuses cross scope, unknown catalog and numeric version',()=>{assert.throws(()=>decodeProviderPresets({version:'2',items:[]}));assert.deepEqual(decodeProviderPresets({version:'2',items:[preset]}),[preset]);assert.throws(()=>decodeProviderObservation({version:2,state:'unavailable',reason:'runtime_unavailable'},id,id));});

test('actual V2 client posts exact selected operation and rejects changed receipt',async()=>{
 const {createCunaApiClient}=await import('../dist/api/client.js');const uuid=n=>`${n}0000000-0000-4000-8000-000000000001`;
 const input={agent:'opencode',operation_id:uuid(6),profile_id:uuid(7),profile_revision:1,execution_workspace_id:uuid(3),workspace_generation:1,cwd:`/workspace/workspaces/${uuid(3)}`};
 const receipt={version:'2',agent_session:{id:uuid(2),machine_id:uuid(1),name:'OpenCode',agent:'opencode',cwd:input.cwd,auth_mode:'interactive_login',desired_state:'running',request_state:'launch_pending',process_state:'unknown',row_version:1,created_at:'2026-09-05T00:00:00Z',updated_at:'2026-09-05T00:00:00Z'},execution_workspace_id:uuid(3),workspace_generation:1,remote_root:input.cwd,selection:{version:'2',kind:'provider_profile_selection',profile_selection_id:uuid(4),operation_id:uuid(6),agent_session_id:uuid(2),session_incarnation:uuid(5),machine_id:uuid(1),profile_id:uuid(7),profile_revision:1,profile_revision_sha256:'a'.repeat(64),configuration_state:'unobserved'}};
 let response=receipt;const calls=[];const client=createCunaApiClient({request:async r=>{calls.push(r);return response;}});
 assert.equal((await client.createProviderSessionV2(uuid(1),input)).agentSession.id,uuid(2));assert.equal(calls[0].path,`/v1/collaboration/2/sessions/${uuid(1)}/workspace-agent-sessions`);assert.equal(calls[0].body.operation_id,input.operation_id);assert.equal(calls[0].idempotencyKey,undefined);
 for(const agent of ['codex','claude-code']){response={...receipt,agent_session:{...receipt.agent_session,agent}};assert.equal((await client.createProviderSessionV2(uuid(1),{...input,agent})).agentSession.agent,agent);assert.equal(calls.at(-1).body.agent,agent);await assert.rejects(client.createProviderSessionV2(uuid(1),input));}
 response={...receipt,selection:{...receipt.selection,profile_revision:2}};await assert.rejects(client.createProviderSessionV2(uuid(1),input));
 await assert.rejects(client.createProviderSessionV2(uuid(1),{...input,extra:'spoof'}));assert.equal(calls.length,6);
});

test('native profile selection filters other agents and makes no observation claim',async()=>{for(const agent of ['codex','claude-code']){const host=new Host();const native={...preset,kind:'native_interactive',agent,label:agent+' native'};const run=runProviderScreen({getProviderPresetsV2:async()=>[preset,native]},{kind:'preset',agent},host);await see(host,native.label);assert.ok(!host.screen.includes(preset.label));assert.match(host.screen,/observation is unavailable/);host.key('\r');assert.deepEqual(await run,native);}});

test('catalog discriminates native and provider profiles without cross-agent alias',()=>{for(const agent of ['codex','claude-code']){const native={...preset,kind:'native_interactive',agent};assert.deepEqual(decodeProviderPresets({version:'2',items:[native]}),[native]);assert.throws(()=>decodeProviderPresets({version:'2',items:[{...native,kind:'provider_preset'}]}));}assert.throws(()=>decodeProviderPresets({version:'2',items:[{...preset,kind:'native_interactive'}]}));});
