import {randomUUID} from 'node:crypto';
import xtermHeadless from '@xterm/headless';
import {createNodeForegroundTerminalHost} from '../pty/node-host-terminal.js';
import type {ForegroundTerminalHost} from '../terminal/foreground.js';
import {MAX_XTERM_CELL_EXTENDERS} from '../terminal/xterm-vte.js';
import {decodeTerminalFrame} from '../terminal/codec.js';
import {sanitizeHumanTerminalOutput} from '../cli/output.js';
import {observerStreamUrl,type observerApi,type ObserverGrant} from '../api/observer-v2.js';

type ReadSocket=Pick<WebSocket,'binaryType'|'onmessage'|'onerror'|'onclose'|'close'>;
export async function runObserverScreen(api:ReturnType<typeof observerApi>,origin:string,host:ForegroundTerminalHost=createNodeForegroundTerminalHost(),signal?:AbortSignal,connect:(url:string,protocols:string[])=>ReadSocket=(url,protocols)=>new WebSocket(url,protocols)):Promise<void>{
 const lease=await host.acquire('rich'),abort=new AbortController(),encoder=new TextEncoder();let stopped=false,busy=false,index=0,after:string|null=null,next:string|null=null,items:ObserverGrant[]=[],selected:ObserverGrant|undefined,socket:ReadSocket|undefined,terminal:InstanceType<typeof xtermHeadless.Terminal>|undefined,timer:ReturnType<typeof setTimeout>|undefined,last=0n,pendingBytes=0,tail=Promise.resolve(),hostWrites=Promise.resolve(),phase:'list'|'connecting'|'observing'|'ended'='list';
 let finish!:()=>void;const done=new Promise<void>(resolve=>{finish=resolve;});
 const write=(text:string,allowed:()=>boolean=()=>true)=>{hostWrites=hostWrites.then(async()=>{if(!stopped&&allowed())await host.write(encoder.encode(text));}).catch(()=>{stop();});return hostWrites;};
 const dispose=()=>{clearTimeout(timer);socket?.close();socket=undefined;terminal?.dispose();terminal=undefined;};
 const stop=()=>{if(stopped)return;stopped=true;abort.abort();dispose();finish();};
 const status=async(message:string)=>{await write('\x1b[H\x1b[2J'+message+'\r\nEsc / Ctrl+C closes this local view.');};
 const ended=(message:string)=>{if(stopped||phase==='ended')return;phase='ended';dispose();void status(message+'\r\nPress r for fresh admission or b to return to sessions.');};
 const menu=async()=>{phase='list';await status('Shared sessions - read-only\r\n'+items.map((g,i)=>`${index===i?'>':' '} ${g.agent_session_id}`).join('\r\n')+'\r\nUp/Down selects; Enter observes; n next page; r refreshes.');};
 const load=async(cursor:string|null)=>{if(busy||stopped)return;busy=true;try{const page=await api.list(cursor,abort.signal);if(stopped)return;items=page.items;after=cursor;next=page.next_after_grant_id;index=0;await menu();if(!items.length)await write('\r\nNo current observation grants on this page.');}catch{if(!stopped)await status('Shared sessions unavailable. Press r to retry.');}finally{busy=false;}};
 const open=async(grant:ObserverGrant)=>{if(busy||stopped)return;busy=true;selected=grant;phase='connecting';last=0n;await status('Requesting current read-only admission...');try{
  const ticket=await api.issue(grant,randomUUID(),randomUUID(),abort.signal);if(stopped)return;const remaining=Math.min(ticket.expires_at,grant.expires_at,Date.now()+15000)-Date.now();if(remaining<=0){ended('Observation admission expired.');return;}
  const size=host.dimensions();terminal=new xtermHeadless.Terminal({cols:Math.max(20,Math.min(160,size.columns)),rows:Math.max(2,Math.min(60,size.rows-2)),scrollback:0,allowProposedApi:true,disableStdin:true});
  const complexity=new TextDecoder();let extenders=0;const activeTerminal=terminal;socket=connect(observerStreamUrl(ticket,origin),['runa.terminal.v1',`runa.auth.${ticket.secret}`]);const activeSocket=socket;socket.binaryType='arraybuffer';
  socket.onmessage=event=>{if(stopped||socket!==activeSocket)return;if(!(event.data instanceof ArrayBuffer)||event.data.byteLength>1048596||pendingBytes+event.data.byteLength>2097192){ended('Observation frame could not be verified.');return;}const bytes=new Uint8Array(event.data);pendingBytes+=bytes.length;tail=tail.then(async()=>{if(stopped||socket!==activeSocket)return;const frame=decodeTerminalFrame(bytes);if(!frame||frame.type!=='output'||frame.sequence<=last)throw Error();if(Date.now()>=grant.expires_at)throw Error();for(const character of complexity.decode(frame.payload,{stream:true})){extenders=/\p{M}|\u200d/u.test(character)?extenders+1:0;if(extenders>MAX_XTERM_CELL_EXTENDERS)throw Error();}const firstFrame=last===0n;last=frame.sequence;if(firstFrame){clearTimeout(timer);timer=setTimeout(()=>{if(socket===activeSocket)ended('Observation grant expired.');},Math.min(2147483647,grant.expires_at-Date.now()));}await new Promise<void>((resolve,reject)=>{const finish=()=>{clearTimeout(bound);abort.signal.removeEventListener('abort',finish);resolve();};const bound=setTimeout(()=>{abort.signal.removeEventListener('abort',finish);reject(Error());},5000);abort.signal.addEventListener('abort',finish,{once:true});activeTerminal.write(frame.payload,finish);});if(stopped||socket!==activeSocket)return;phase='observing';const buffer=activeTerminal.buffer.active;const rows=Array.from({length:activeTerminal.rows},(_,i)=>sanitizeHumanTerminalOutput(buffer.getLine(buffer.viewportY+i)?.translateToString(true)??''));await write('\x1b[H\x1b[2JObserving read-only - Esc / Ctrl+C closes\r\n'+rows.join('\r\n'),()=>socket===activeSocket);}).catch(()=>{if(socket===activeSocket)ended('Observation could not be verified.');}).finally(()=>{pendingBytes-=bytes.length;});};
  socket.onerror=()=>{if(socket===activeSocket)ended('Observation unavailable or access refused.');};socket.onclose=()=>{if(socket===activeSocket)ended('Observation ended. Access may have expired or been withdrawn.');};timer=setTimeout(()=>ended('Observation expired. Fresh admission is required.'),remaining);
 }catch{if(!stopped)ended('Observation unavailable. Ask the owner to check publication and access.');}finally{busy=false;}};
 const remove=host.onInput(bytes=>{if(stopped)return;const key=new TextDecoder().decode(bytes);if(key==='\x03'||key==='\x1b'){stop();return;}if(busy)return;if(phase==='list'){if(key==='\x1b[A'){index=Math.max(0,index-1);void menu();}else if(key==='\x1b[B'){index=Math.min(items.length-1,index+1);void menu();}else if(key==='\r'&&items[index])void open(items[index]!);else if(key==='n'&&next)void load(next);else if(key==='r')void load(after);}else if(phase==='ended'){if(key==='r'&&selected)void open(selected);else if(key==='b')void load(null);}});
 signal?.addEventListener('abort',stop,{once:true});try{if(signal?.aborted)stop();else void load(null);await done;}finally{stop();remove();signal?.removeEventListener('abort',stop);await tail.catch(()=>{});await hostWrites;await lease.restore();}
}
