import type { CunaApiClient } from '../api/client.js';
import type { ProviderAgent, ProviderPreset, ProviderObservation } from '../api/provider-v2.js';
import { createNodeForegroundTerminalHost } from '../pty/node-host-terminal.js';
import type { ForegroundTerminalHost } from '../terminal/foreground.js';
import { sanitizeHumanTerminalOutput } from '../cli/output.js';
import { truncateTerminalLine } from '../terminal/cell-width.js';

/** One explicit pull; expiry repaints locally and never polls the provider. */
export async function runProviderScreen(client:CunaApiClient, mode:{kind:'preset';agent:ProviderAgent}|{kind:'check';sessionId:string}, host:ForegroundTerminalHost=createNodeForegroundTerminalHost(), signal?:AbortSignal):Promise<ProviderPreset|undefined> {
 const lease=await host.acquire('rich');const abort=new AbortController();let closed=false,busy=false,index=0,notice='',items:readonly ProviderPreset[]=[],observation:ProviderObservation|undefined;
 let timer:ReturnType<typeof setTimeout>|undefined;let writes=Promise.resolve();let resolve!:(v:ProviderPreset|undefined)=>void;const done=new Promise<ProviderPreset|undefined>(r=>{resolve=r;});
 const close=(value?:ProviderPreset)=>{if(closed)return;closed=true;abort.abort();resolve(value);};
 const render=()=>{if(closed)return;const size=host.dimensions();const lines=mode.kind==='preset'?[` New ${mode.agent} session - select profile`,...items.map((p,i)=>`${i===index?' >':'  '} ${p.label}`),mode.agent==='opencode'?' Connect your provider and select this model in OpenCode after launch.':' Native interactive login; provider observation is unavailable.',' Enter selects / r refresh / Esc or q returns']:[' Check provider and model'];
 if(mode.kind==='check') {if(observation?.state==='observed'&&observation.observed_at_ms<=Date.now()&&observation.valid_until_ms>Date.now())lines.push(` Provider: ${observation.provider.upstream_provider}`,` Model: ${observation.provider.model}`,` Agent version: ${observation.provider.agent_version}`,` Expires: ${new Date(observation.valid_until_ms).toISOString()}`);else lines.push(' Provider and model unavailable.');lines.push(' r Check provider / Esc or q returns');}
 if(busy)lines.push(' Reading server state...');if(notice)lines.push(notice);
 const frame='\x1b[H\x1b[2J'+lines.slice(0,Math.max(1,size.rows-1)).map(l=>truncateTerminalLine(sanitizeHumanTerminalOutput(l),size.columns)).join('\r\n');writes=writes.then(()=>closed?undefined:host.write(new TextEncoder().encode(frame))).catch(()=>close());};
 const load=async()=>{if(busy||closed)return;busy=true;observation=undefined;notice='';if(timer)clearTimeout(timer);render();try{if(mode.kind==='preset'){items=(await client.getProviderPresetsV2(abort.signal)).filter(p=>p.agent===mode.agent);index=0;if(!items.length)notice=' No matching profiles are available for this agent.';}else{const session=await client.getAgentSession(mode.sessionId,abort.signal);if(!session.processEpoch)throw Error('scope');const result=await client.checkProviderV2(session.id,session.processEpoch,abort.signal);const current=await client.getAgentSession(session.id,abort.signal);if(current.processEpoch!==session.processEpoch||current.desiredState!=='running'||!['ready','running'].includes(current.processState))throw Error('scope');abort.signal.throwIfAborted();observation=result;if(result.state==='observed')timer=setTimeout(()=>{observation=undefined;notice=' Observation expired. Press r to check again.';render();},Math.max(0,result.valid_until_ms-Date.now()));}}catch{items=[];observation=undefined;notice=' Provider information unavailable. Press r to try again.';}finally{busy=false;render();}};
 let sequence='';let paste=false;
 const input=host.onInput(bytes=>{for(const byte of bytes){if(sequence){sequence+=String.fromCharCode(byte);if(sequence==='\x1b[200~'){paste=true;sequence='';}else if(sequence==='\x1b[201~'){paste=false;sequence='';}else if(sequence==='\x1b[A'||sequence==='\x1b[B'){if(!paste&&!busy){index=Math.max(0,Math.min(items.length-1,index+(sequence.endsWith('A')?-1:1)));render();}sequence='';}else if(sequence.length>8)sequence='';continue;}if(byte===27){sequence='\x1b';setTimeout(()=>{if(sequence==='\x1b'){sequence='';close();}},50);continue;}if(paste)continue;if(byte===3||byte===113){close();return;}if(byte===114)void load();if((byte===13||byte===10)&&!busy&&mode.kind==='preset'&&items[index])close(items[index]);}});
 const resize=host.onResize(render);const onAbort=()=>close();signal?.addEventListener('abort',onAbort,{once:true});if(signal?.aborted)close();else void load();
 try{return await done;}finally{input();resize();signal?.removeEventListener('abort',onAbort);if(timer)clearTimeout(timer);await writes;await lease.restore();}
}
