/* oxlint-disable unicorn/no-thenable -- JSON Schema conditional keyword */
// Generated by scripts/project-observer-v2.mjs from contracts/infra/cuna-api.openapi.json; SHA256 273feaa7c5ed9552ef68486cf7461631df630729a6fbb682c0d78f6555a2e2e5
export const observerSchemas={
  "ListObserverSessionsV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "after_grant_id": {
        "anyOf": [
          {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          {
            "type": "null"
          }
        ]
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    }
  },
  "ObserverSessionsV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "project_id",
      "items",
      "next_after_grant_id"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "kind": {
        "const": "observer_sessions"
      },
      "project_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "items": {
        "type": "array",
        "maxItems": 100,
        "items": {
          "$ref": "#/components/schemas/SessionObserveGrantV2Receipt"
        }
      },
      "next_after_grant_id": {
        "anyOf": [
          {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "SessionObserveGrantV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "grant_id",
      "revision",
      "owner_principal_id",
      "subject_principal_id",
      "agent_session_id",
      "session_incarnation",
      "project_id",
      "authority_epoch",
      "membership_revision",
      "state",
      "expires_at",
      "revocation_state"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "kind": {
        "type": "string",
        "const": "session_observe_grant"
      },
      "grant_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "owner_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "subject_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "agent_session_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "project_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "authority_epoch": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "membership_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "state": {
        "type": "string",
        "enum": [
          "active",
          "revoking",
          "revoked",
          "expired"
        ]
      },
      "expires_at": {
        "type": "integer",
        "minimum": 0,
        "maximum": 253402300799999
      },
      "revocation_state": {
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "effective_pending",
          "effective",
          null
        ]
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "state": {
              "const": "active"
            }
          }
        },
        "then": {
          "properties": {
            "revocation_state": {
              "type": "null"
            }
          }
        },
        "else": {
          "properties": {
            "revocation_state": {
              "type": "string",
              "enum": [
                "effective_pending",
                "effective"
              ]
            }
          }
        }
      }
    ]
  },
  "IssueObserverAttachmentV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "client_instance_id"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "client_instance_id": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9._:-]+$"
      }
    }
  },
  "ObserverAttachmentV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "attachment_id",
      "expires_at",
      "secret",
      "stream_path"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "attachment_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "expires_at": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "secret": {
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{43}$"
      },
      "stream_path": {
        "type": "string",
        "pattern": "^/v1/collaboration/2/observer-attachments/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/stream$"
      }
    }
  }
} as const;
export const observerOperations={
  "listObserverSessionsV2": {
    "path": "/v1/collaboration/2/projects/{id}/observer-sessions",
    "method": "POST"
  },
  "issueObserverAttachmentV2": {
    "path": "/v1/collaboration/2/observe-grants/{id}/attachments",
    "method": "POST"
  }
} as const;
