/* oxlint-disable unicorn/no-thenable -- JSON Schema conditional keyword */
// Generated by scripts/project-owner-observe-grants-v2.mjs from contracts/infra/cuna-api.openapi.json; SHA256 a0da25fba2bc268a3fa7e77e3c659f102d8ded28c88e89f76160f2daff1b13f3
export const ownerObserveGrantSchemas={
  "ListProjectObserversV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "after_principal_id": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
        "default": null
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100,
        "default": 50
      }
    }
  },
  "ProjectObserversV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "project_id",
      "authority_epoch",
      "items",
      "next_after_principal_id"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "kind": {
        "type": "string",
        "const": "project_observers"
      },
      "project_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "authority_epoch": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "items": {
        "type": "array",
        "maxItems": 100,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "principal_id",
            "membership_revision",
            "recipient_email"
          ],
          "properties": {
            "principal_id": {
              "type": "string",
              "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
            },
            "membership_revision": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            },
            "recipient_email": {
              "type": [
                "string",
                "null"
              ],
              "format": "email",
              "maxLength": 254
            }
          }
        }
      },
      "next_after_principal_id": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      }
    }
  },
  "CreateSessionObserveGrantV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "subject_principal_id",
      "expected_membership_revision",
      "expires_at_ms"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "subject_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "expected_membership_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "expires_at_ms": {
        "type": "integer",
        "minimum": 0,
        "maximum": 253402300799999
      }
    }
  },
  "InspectSessionObserveGrantV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      }
    }
  },
  "RevokeSessionObserveGrantV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "expected_revision"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "expected_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      }
    }
  },
  "SessionObserveGrantV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "grant_id",
      "revision",
      "owner_principal_id",
      "subject_principal_id",
      "agent_session_id",
      "session_incarnation",
      "project_id",
      "authority_epoch",
      "membership_revision",
      "state",
      "expires_at",
      "revocation_state"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "kind": {
        "type": "string",
        "const": "session_observe_grant"
      },
      "grant_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "owner_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "subject_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "agent_session_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "project_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "authority_epoch": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "membership_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "state": {
        "type": "string",
        "enum": [
          "active",
          "revoking",
          "revoked",
          "expired"
        ]
      },
      "expires_at": {
        "type": "integer",
        "minimum": 0,
        "maximum": 253402300799999
      },
      "revocation_state": {
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "effective_pending",
          "effective",
          null
        ]
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "state": {
              "const": "active"
            }
          }
        },
        "then": {
          "properties": {
            "revocation_state": {
              "type": "null"
            }
          }
        },
        "else": {
          "properties": {
            "revocation_state": {
              "type": "string",
              "enum": [
                "effective_pending",
                "effective"
              ]
            }
          }
        }
      }
    ]
  }
} as const;
export const ownerObserveGrantOperations={
  "listProjectObserversV2": {
    "path": "/v1/collaboration/2/projects/{id}/observers",
    "method": "POST"
  },
  "createSessionObserveGrantV2": {
    "path": "/v1/collaboration/2/agent-sessions/{id}/observe-grants",
    "method": "POST"
  },
  "inspectSessionObserveGrantV2": {
    "path": "/v1/collaboration/2/observe-grants/{id}/inspect",
    "method": "POST"
  },
  "revokeSessionObserveGrantV2": {
    "path": "/v1/collaboration/2/observe-grants/{id}/revoke",
    "method": "POST"
  }
} as const;
