/* oxlint-disable unicorn/no-thenable -- JSON Schema conditional keyword */
// Generated by scripts/project-owner-observe-grants-v2.mjs from contracts/infra/cuna-api.openapi.json; SHA256 f4c2d396b94f296b22df276435dc04ecf1da48807efa1e819c4cbff9ea59a83e
export const ownerObserveGrantSchemas={
  "ListProjectObserversV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "after_principal_id": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
        "default": null
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100,
        "default": 50
      }
    }
  },
  "ProjectObserversV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "project_id",
      "authority_epoch",
      "items",
      "next_after_principal_id"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "kind": {
        "type": "string",
        "const": "project_observers"
      },
      "project_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "authority_epoch": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "items": {
        "type": "array",
        "maxItems": 100,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "principal_id",
            "membership_revision",
            "recipient_email"
          ],
          "properties": {
            "principal_id": {
              "type": "string",
              "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
            },
            "membership_revision": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            },
            "recipient_email": {
              "type": [
                "string",
                "null"
              ],
              "format": "email",
              "maxLength": 254
            }
          }
        }
      },
      "next_after_principal_id": {
        "type": [
          "string",
          "null"
        ],
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      }
    }
  },
  "CreateSessionObserveGrantV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "subject_principal_id",
      "expected_membership_revision",
      "expires_at_ms"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "subject_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "expected_membership_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "expires_at_ms": {
        "type": "integer",
        "minimum": 0,
        "maximum": 253402300799999
      }
    }
  },
  "InspectSessionObserveGrantV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      }
    }
  },
  "RevokeSessionObserveGrantV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "expected_revision"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "expected_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      }
    }
  },
  "SessionObserveGrantV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "grant_id",
      "revision",
      "owner_principal_id",
      "subject_principal_id",
      "agent_session_id",
      "session_incarnation",
      "project_id",
      "authority_epoch",
      "membership_revision",
      "state",
      "expires_at",
      "revocation_state"
    ],
    "properties": {
      "version": {
        "type": "string",
        "const": "2"
      },
      "kind": {
        "type": "string",
        "const": "session_observe_grant"
      },
      "grant_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "owner_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "subject_principal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "agent_session_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "project_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "authority_epoch": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "membership_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "state": {
        "type": "string",
        "enum": [
          "active",
          "revoking",
          "revoked",
          "expired"
        ]
      },
      "expires_at": {
        "type": "integer",
        "minimum": 0,
        "maximum": 253402300799999
      },
      "revocation_state": {
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "effective_pending",
          "effective",
          null
        ]
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "state": {
              "const": "active"
            }
          }
        },
        "then": {
          "properties": {
            "revocation_state": {
              "type": "null"
            }
          }
        },
        "else": {
          "properties": {
            "revocation_state": {
              "type": "string",
              "enum": [
                "effective_pending",
                "effective"
              ]
            }
          }
        }
      }
    ]
  },
  "PrepareSessionAudienceV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "action"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "action": {
        "enum": [
          "publish",
          "private"
        ]
      }
    }
  },
  "PrepareSessionAudienceV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "state",
      "response"
    ],
    "properties": {
      "state": {
        "const": "observed"
      },
      "response": {
        "$ref": "#/components/schemas/ObservedSessionAudienceResponseV2"
      }
    }
  },
  "ObservedSessionAudienceResponseV2": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "version",
      "request_id",
      "action",
      "agent_session_id",
      "session_incarnation",
      "process_epoch",
      "runtime_lease_id",
      "logical_terminal_id",
      "process_start_identity",
      "expected_generation",
      "result"
    ],
    "properties": {
      "type": {
        "const": "session_audience_response_v2"
      },
      "version": {
        "const": "2"
      },
      "request_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "action": {
        "enum": [
          "publish",
          "private"
        ]
      },
      "agent_session_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "process_epoch": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "runtime_lease_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "logical_terminal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "process_start_identity": {
        "type": "string",
        "pattern": "^[1-9][0-9]{0,31}$"
      },
      "expected_generation": {
        "type": "string",
        "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
      },
      "result": {
        "anyOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "status",
              "state",
              "stream_id",
              "generation",
              "first_sequence"
            ],
            "properties": {
              "status": {
                "const": "observed"
              },
              "state": {
                "const": "public"
              },
              "stream_id": {
                "type": "string",
                "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
              },
              "generation": {
                "type": "string",
                "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
              },
              "first_sequence": {
                "const": "1"
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "status",
              "state",
              "generation"
            ],
            "properties": {
              "status": {
                "const": "observed"
              },
              "state": {
                "const": "private"
              },
              "generation": {
                "type": "string",
                "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
              }
            }
          }
        ]
      }
    }
  },
  "ReadSessionAudienceStateV2Request": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id"
    ],
    "description": "Reads the current audience. Never publishes and never admits an observer. Supply reconcile_operation_id to also receive what one earlier transition is recorded to have done.",
    "properties": {
      "version": {
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "reconcile_operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      }
    }
  },
  "SessionAudienceStateV2Receipt": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "state",
      "current"
    ],
    "properties": {
      "state": {
        "const": "reconciled"
      },
      "current": {
        "$ref": "#/components/schemas/ObservedSessionAudienceStateV2"
      },
      "operation": {
        "$ref": "#/components/schemas/SessionAudienceOperationV2"
      }
    }
  },
  "ObservedSessionAudienceStateV2": {
    "type": "object",
    "additionalProperties": false,
    "description": "A fresh fence-bound reading of the live runtime. The generation is the runtime's own; after a publication whose acknowledgement was lost it is ahead of every recorded transition. No first_sequence is present because a reading opens no stream.",
    "required": [
      "type",
      "version",
      "request_id",
      "agent_session_id",
      "session_incarnation",
      "process_epoch",
      "runtime_lease_id",
      "logical_terminal_id",
      "process_start_identity",
      "expected_generation",
      "result",
      "action"
    ],
    "properties": {
      "type": {
        "const": "session_audience_response_v2"
      },
      "version": {
        "const": "2"
      },
      "request_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "agent_session_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "process_epoch": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "runtime_lease_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "logical_terminal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "process_start_identity": {
        "type": "string",
        "pattern": "^[1-9][0-9]{0,31}$"
      },
      "expected_generation": {
        "type": "string",
        "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
      },
      "action": {
        "const": "observe"
      },
      "result": {
        "anyOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "status",
              "state",
              "stream_id",
              "generation"
            ],
            "properties": {
              "status": {
                "const": "observed"
              },
              "state": {
                "const": "public"
              },
              "stream_id": {
                "type": "string",
                "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
              },
              "generation": {
                "type": "string",
                "pattern": "^(?:[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "status",
              "state",
              "generation"
            ],
            "properties": {
              "status": {
                "const": "observed"
              },
              "state": {
                "const": "private"
              },
              "generation": {
                "type": "string",
                "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
              }
            }
          }
        ]
      }
    }
  },
  "SessionAudienceOperationV2": {
    "description": "What one earlier operation is recorded to have done. status=expired_unrecorded means its deadline passed with no recorded response: the effect is unknown and expiry is not an acknowledgement. status=unknown means no such operation was ever issued.",
    "oneOf": [
      {
        "type": "object",
        "additionalProperties": false,
        "description": "No such operation was ever issued for this session.",
        "required": [
          "version",
          "kind",
          "operation_id",
          "status"
        ],
        "properties": {
          "version": {
            "const": "2"
          },
          "kind": {
            "const": "session_audience_operation"
          },
          "operation_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "status": {
            "const": "unknown"
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "description": "The operation has a durable answer. It is history, not a statement about now.",
        "required": [
          "version",
          "kind",
          "operation_id",
          "status",
          "agent_session_id",
          "action",
          "request_revision",
          "issued_at_ms",
          "deadline_ms",
          "response"
        ],
        "properties": {
          "version": {
            "const": "2"
          },
          "kind": {
            "const": "session_audience_operation"
          },
          "operation_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "status": {
            "const": "recorded"
          },
          "agent_session_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          },
          "action": {
            "enum": [
              "publish",
              "private",
              "observe"
            ]
          },
          "request_revision": {
            "type": "string",
            "pattern": "^[1-9][0-9]{0,15}$"
          },
          "issued_at_ms": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "deadline_ms": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "response": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/ObservedSessionAudienceResponseV2"
              },
              {
                "$ref": "#/components/schemas/ObservedSessionAudienceStateV2"
              },
              {
                "$ref": "#/components/schemas/RefusedSessionAudienceResponseV2"
              }
            ]
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "description": "The operation has no recorded answer: still inside its deadline, or past it with the effect unknown. Expiry is not an acknowledgement.",
        "required": [
          "version",
          "kind",
          "operation_id",
          "status",
          "agent_session_id",
          "action",
          "request_revision",
          "issued_at_ms",
          "deadline_ms",
          "response"
        ],
        "properties": {
          "version": {
            "const": "2"
          },
          "kind": {
            "const": "session_audience_operation"
          },
          "operation_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "status": {
            "enum": [
              "pending",
              "expired_unrecorded"
            ]
          },
          "agent_session_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          },
          "action": {
            "enum": [
              "publish",
              "private",
              "observe"
            ]
          },
          "request_revision": {
            "type": "string",
            "pattern": "^[1-9][0-9]{0,15}$"
          },
          "issued_at_ms": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "deadline_ms": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "response": {
            "type": "null"
          }
        }
      }
    ]
  },
  "RefusedSessionAudienceResponseV2": {
    "type": "object",
    "additionalProperties": false,
    "description": "A durable record that the runtime refused to answer one request. It says nothing about the audience: it names no state, no stream and no generation.",
    "required": [
      "type",
      "version",
      "request_id",
      "action",
      "agent_session_id",
      "session_incarnation",
      "process_epoch",
      "runtime_lease_id",
      "logical_terminal_id",
      "process_start_identity",
      "expected_generation",
      "result"
    ],
    "properties": {
      "type": {
        "const": "session_audience_response_v2"
      },
      "version": {
        "const": "2"
      },
      "request_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "agent_session_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "process_epoch": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "runtime_lease_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "logical_terminal_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "process_start_identity": {
        "type": "string",
        "pattern": "^[1-9][0-9]{0,31}$"
      },
      "expected_generation": {
        "type": "string",
        "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
      },
      "action": {
        "enum": [
          "publish",
          "private",
          "observe"
        ]
      },
      "result": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "status",
          "reason"
        ],
        "properties": {
          "status": {
            "const": "unavailable"
          },
          "reason": {
            "enum": [
              "session_unavailable",
              "audience_stale",
              "deadline_expired",
              "runtime_unavailable"
            ]
          }
        }
      }
    }
  }
} as const;
export const ownerObserveGrantOperations={
  "listProjectObserversV2": {
    "path": "/v1/collaboration/2/projects/{id}/observers",
    "method": "POST"
  },
  "createSessionObserveGrantV2": {
    "path": "/v1/collaboration/2/agent-sessions/{id}/observe-grants",
    "method": "POST"
  },
  "inspectSessionObserveGrantV2": {
    "path": "/v1/collaboration/2/observe-grants/{id}/inspect",
    "method": "POST"
  },
  "revokeSessionObserveGrantV2": {
    "path": "/v1/collaboration/2/observe-grants/{id}/revoke",
    "method": "POST"
  },
  "prepareSessionAudienceV2": {
    "path": "/v1/collaboration/2/agent-sessions/{id}/audience",
    "method": "POST"
  },
  "readSessionAudienceStateV2": {
    "path": "/v1/collaboration/2/agent-sessions/{id}/audience-state",
    "method": "POST"
  }
} as const;
