/* oxlint-disable unicorn/no-thenable -- JSON Schema conditional keyword */
// Generated by scripts/project-provider-v2.mjs; source SHA256 a7537a26fe20afb459f642362b5c335122e1e42d0ed2713a5475399d114551fc
export const providerV2Schemas = {
  "ProviderProfileCatalogResponseV2": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "items"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "items": {
        "type": "array",
        "minItems": 1,
        "maxItems": 3,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "label",
            "profile_id",
            "profile_revision",
            "kind",
            "agent"
          ],
          "properties": {
            "label": {
              "type": "string",
              "minLength": 1,
              "maxLength": 160
            },
            "profile_id": {
              "type": "string",
              "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
            },
            "profile_revision": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            },
            "kind": {
              "enum": [
                "provider_preset",
                "native_interactive"
              ]
            },
            "agent": {
              "enum": [
                "opencode",
                "codex",
                "claude-code"
              ]
            }
          },
          "allOf": [
            {
              "if": {
                "properties": {
                  "kind": {
                    "const": "provider_preset"
                  }
                },
                "required": [
                  "kind"
                ]
              },
              "then": {
                "properties": {
                  "agent": {
                    "const": "opencode"
                  }
                }
              },
              "else": {
                "properties": {
                  "agent": {
                    "enum": [
                      "codex",
                      "claude-code"
                    ]
                  }
                }
              }
            }
          ]
        }
      }
    }
  },
  "ProviderObservationResponseV2": {
    "oneOf": [
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "state",
          "agent_session_id",
          "process_epoch",
          "observed_at_ms",
          "valid_until_ms",
          "provider",
          "dispatch_id",
          "session_incarnation",
          "profile_selection_id",
          "profile_id",
          "observation_id",
          "profile_revision",
          "profile_revision_sha256",
          "observation_revision"
        ],
        "properties": {
          "version": {
            "const": "2"
          },
          "state": {
            "const": "observed"
          },
          "agent_session_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          },
          "process_epoch": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          },
          "observed_at_ms": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "valid_until_ms": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "provider": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "upstream_provider",
              "agent_version",
              "model",
              "effective_config_sha256",
              "adapter_identity_sha256"
            ],
            "properties": {
              "upstream_provider": {
                "type": "string",
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$"
              },
              "agent_version": {
                "type": "string",
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:+-]{0,127}$"
              },
              "model": {
                "type": "string",
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$"
              },
              "effective_config_sha256": {
                "type": "string",
                "pattern": "^[0-9a-f]{64}$"
              },
              "adapter_identity_sha256": {
                "type": "string",
                "pattern": "^[0-9a-f]{64}$"
              }
            }
          },
          "dispatch_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          },
          "session_incarnation": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "profile_selection_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "profile_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "observation_id": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          },
          "profile_revision": {
            "type": "integer",
            "minimum": 1,
            "maximum": 9007199254740991
          },
          "profile_revision_sha256": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          },
          "observation_revision": {
            "type": "integer",
            "minimum": 1,
            "maximum": 9007199254740991
          }
        }
      },
      {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "state",
          "reason"
        ],
        "properties": {
          "version": {
            "const": "2"
          },
          "state": {
            "const": "unavailable"
          },
          "reason": {
            "type": "string",
            "enum": [
              "runtime_unavailable",
              "invalid_scope",
              "request_unavailable",
              "transport_unavailable",
              "response_unavailable",
              "receipt_unavailable",
              "current_fact_unavailable"
            ]
          }
        }
      }
    ]
  },
  "ProviderSessionCreateRequestV2": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "operation_id",
      "execution_workspace_id",
      "workspace_generation",
      "agent",
      "cwd",
      "auth_mode",
      "profile_id",
      "profile_revision"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "execution_workspace_id": {
        "$ref": "#/components/schemas/Uuid"
      },
      "workspace_generation": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 80
      },
      "agent": {
        "enum": [
          "claude-code",
          "codex",
          "opencode"
        ]
      },
      "cwd": {
        "type": "string",
        "minLength": 10,
        "maxLength": 1024,
        "pattern": "^/workspace/workspaces/[0-9a-f-]+(?:/.*)?$"
      },
      "auth_mode": {
        "const": "interactive_login"
      },
      "profile_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "profile_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      }
    },
    "description": "operation_id is the sole stable idempotency identity. Retry the identical request with the same UUIDv4. The profile is immutable expected configuration, never a provider permission or login fact."
  },
  "ProviderSessionSelectionV2": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "version",
      "kind",
      "profile_selection_id",
      "operation_id",
      "agent_session_id",
      "session_incarnation",
      "machine_id",
      "profile_id",
      "profile_revision",
      "profile_revision_sha256",
      "configuration_state"
    ],
    "properties": {
      "version": {
        "const": "2"
      },
      "kind": {
        "const": "provider_profile_selection"
      },
      "profile_selection_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "operation_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "agent_session_id": {
        "$ref": "#/components/schemas/Uuid"
      },
      "session_incarnation": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "machine_id": {
        "$ref": "#/components/schemas/Uuid"
      },
      "profile_id": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "profile_revision": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "profile_revision_sha256": {
        "type": "string",
        "pattern": "^[0-9a-f]{64}$"
      },
      "configuration_state": {
        "const": "unobserved"
      }
    }
  },
  "Uuid": {
    "type": "string",
    "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  }
} as const;
export const providerV2Operations = {
  "providerProfiles.catalogV2": {
    "path": "/v1/collaboration/2/provider-profiles/catalog",
    "method": "POST"
  },
  "agentSessions.createProviderSessionV2": {
    "path": "/v1/collaboration/2/sessions/{id}/workspace-agent-sessions",
    "method": "POST"
  },
  "agentSessions.providerObservationV2": {
    "path": "/v1/collaboration/2/agent-sessions/{id}/provider-observations",
    "method": "POST"
  }
} as const;
